### ISSUE TITLE
電話番号認証なしのアカウントでも書き込めるチャンネルが欲しいです

### ISSUE THREAD

**Issue by tadanonekozuki** [nekosaba/nekosaba-readme#3]
可能なら。。。

**Comment by g00cey** [comment]
@tadanonekozuki 
電話番号認証なしでも書き込めるようにした際のデメリットは割とあるかな？と思ってるんですが（わざわざそこまで敷居下げなくても感ですね）
これにより解消したい問題はなんですか？

**Comment by tadanonekozuki** [comment]
私が書き込めない問題だけです！

**Comment by g00cey** [comment]
サーバー内の結果をもとに管理者間で協議した結果、SMS認証を外したチャンネルを用意しないことになりました。
ご了承ください。
